# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-uEgU_Hq3wQnPZ-pVFWz9dRUUhwlby06
"""

#pip install replicate

#r8_SWp24LJcA2yFiXklelFnK6puztNtxjv20hxYk

# Commented out IPython magic to ensure Python compatibility.
# %env REPLICATE_API_TOKEN= r8_SWp24LJcA2yFiXklelFnK6puztNtxjv20hxYk

import replicate

output = replicate.run(
    "yorickvp/llava-13b:e272157381e2a3bf12df3a8edd1f38d1dbd736bbb7437277c8b34175f8fce358",
    input={
        "image": "' '.join",
        "top_p": 1,
        "prompt": "Are you allowed to swim here?",
        "max_tokens": 1024,
        "temperature": 0.2
    }
)
print(' '.join(output))
